### Cadastrar pessoa
POST http://localhost:3000/newPessoa
Content-Type: application/json

{
    "nome": "Ana Maria Vargas",
    "email": "vargas@hotmail.com",
    "area_id": 12,
    "tp_coord": "S",
    "coord_id": 20
}