### Cadastrar pessoa
POST http://localhost:3000/newPessoa
Content-Type: application/json

{
    "name": "Ana Vargas",
    "email": "ana@gmail.com",
    "area_id": 12,
    "tp_coord": "S",
    "coord_id": 1
}